/**
 * Mock intelligence data hook — provides static bairro data
 * without requiring a Supabase connection.
 */
import { useQuery } from "@tanstack/react-query";
import type { BairroAirbnb } from "@/types/intelligence";

const MOCK_BAIRROS: BairroAirbnb[] = [
  { id: 1, bairro: "Vila Mariana", cidade: "São Paulo", periodo_inicio: "2025-01", periodo_fim: "2025-12", n_listings_total: 420, n_listings_studio_1q: 180, pct_studio_1q: 42.9, adr_medio_studio: 366, ocupacao_media_studio: 0.80, receita_anual_media_studio: 106904, estadia_media_noites: 3.2, porcentagem_reservas_30d_plus: 8, rating_medio: 4.6, percentual_superhost: 35, media_reviews_por_listing: 28, pct_politica_flexivel: 60, pct_politica_moderada: 30, pct_politica_rigida: 10, preco_m2_residencial_medio: 11500, aluguel_mensal_long_term_medio: 3200, dias_medio_venda_imovel: 120, numero_transacoes_imobiliarias_ano: 850, indice_criminalidade: 3.2, grau_saturacao_index: 45, risco_regulatorio: 2, risco_condominio: 3, area_media_estudio: 28, yield_bruto_airbnb: 0.332, yield_bruto_long_term: 0.119, delta_yield: 0.213, score_rentabilidade: 88, score_liquidez: 78, score_crescimento_potencial: 70, nivel_confianca_dados: "alto", fonte_primaria: "AirDNA", data_atualizacao: "2026-03-01" },
  { id: 2, bairro: "Pinheiros", cidade: "São Paulo", periodo_inicio: "2025-01", periodo_fim: "2025-12", n_listings_total: 580, n_listings_studio_1q: 250, pct_studio_1q: 43.1, adr_medio_studio: 350, ocupacao_media_studio: 0.82, receita_anual_media_studio: 104790, estadia_media_noites: 2.8, porcentagem_reservas_30d_plus: 5, rating_medio: 4.7, percentual_superhost: 42, media_reviews_por_listing: 35, pct_politica_flexivel: 55, pct_politica_moderada: 35, pct_politica_rigida: 10, preco_m2_residencial_medio: 14000, aluguel_mensal_long_term_medio: 4200, dias_medio_venda_imovel: 90, numero_transacoes_imobiliarias_ano: 1200, indice_criminalidade: 2.8, grau_saturacao_index: 55, risco_regulatorio: 2, risco_condominio: 2, area_media_estudio: 30, yield_bruto_airbnb: 0.137, yield_bruto_long_term: 0.072, delta_yield: 0.065, score_rentabilidade: 80, score_liquidez: 85, score_crescimento_potencial: 75, nivel_confianca_dados: "alto", fonte_primaria: "AirDNA", data_atualizacao: "2026-03-01" },
  { id: 3, bairro: "Consolação", cidade: "São Paulo", periodo_inicio: "2025-01", periodo_fim: "2025-12", n_listings_total: 350, n_listings_studio_1q: 160, pct_studio_1q: 45.7, adr_medio_studio: 260, ocupacao_media_studio: 0.76, receita_anual_media_studio: 72124, estadia_media_noites: 3.0, porcentagem_reservas_30d_plus: 10, rating_medio: 4.5, percentual_superhost: 30, media_reviews_por_listing: 22, pct_politica_flexivel: 65, pct_politica_moderada: 25, pct_politica_rigida: 10, preco_m2_residencial_medio: 10500, aluguel_mensal_long_term_medio: 2800, dias_medio_venda_imovel: 130, numero_transacoes_imobiliarias_ano: 600, indice_criminalidade: 3.8, grau_saturacao_index: 40, risco_regulatorio: 3, risco_condominio: 3, area_media_estudio: 26, yield_bruto_airbnb: 0.118, yield_bruto_long_term: 0.062, delta_yield: 0.056, score_rentabilidade: 68, score_liquidez: 65, score_crescimento_potencial: 72, nivel_confianca_dados: "médio", fonte_primaria: "AirDNA", data_atualizacao: "2026-03-01" },
  { id: 4, bairro: "Bela Vista", cidade: "São Paulo", periodo_inicio: "2025-01", periodo_fim: "2025-12", n_listings_total: 400, n_listings_studio_1q: 200, pct_studio_1q: 50.0, adr_medio_studio: 240, ocupacao_media_studio: 0.74, receita_anual_media_studio: 64896, estadia_media_noites: 3.5, porcentagem_reservas_30d_plus: 12, rating_medio: 4.4, percentual_superhost: 25, media_reviews_por_listing: 20, pct_politica_flexivel: 70, pct_politica_moderada: 20, pct_politica_rigida: 10, preco_m2_residencial_medio: 9800, aluguel_mensal_long_term_medio: 2500, dias_medio_venda_imovel: 140, numero_transacoes_imobiliarias_ano: 500, indice_criminalidade: 4.2, grau_saturacao_index: 50, risco_regulatorio: 3, risco_condominio: 4, area_media_estudio: 25, yield_bruto_airbnb: 0.112, yield_bruto_long_term: 0.058, delta_yield: 0.054, score_rentabilidade: 65, score_liquidez: 60, score_crescimento_potencial: 65, nivel_confianca_dados: "médio", fonte_primaria: "AirDNA", data_atualizacao: "2026-03-01" },
  { id: 5, bairro: "Itaim Bibi", cidade: "São Paulo", periodo_inicio: "2025-01", periodo_fim: "2025-12", n_listings_total: 520, n_listings_studio_1q: 220, pct_studio_1q: 42.3, adr_medio_studio: 380, ocupacao_media_studio: 0.78, receita_anual_media_studio: 108186, estadia_media_noites: 2.5, porcentagem_reservas_30d_plus: 4, rating_medio: 4.7, percentual_superhost: 45, media_reviews_por_listing: 32, pct_politica_flexivel: 50, pct_politica_moderada: 40, pct_politica_rigida: 10, preco_m2_residencial_medio: 16000, aluguel_mensal_long_term_medio: 5000, dias_medio_venda_imovel: 80, numero_transacoes_imobiliarias_ano: 1400, indice_criminalidade: 2.5, grau_saturacao_index: 60, risco_regulatorio: 2, risco_condominio: 2, area_media_estudio: 32, yield_bruto_airbnb: 0.142, yield_bruto_long_term: 0.078, delta_yield: 0.064, score_rentabilidade: 82, score_liquidez: 82, score_crescimento_potencial: 68, nivel_confianca_dados: "alto", fonte_primaria: "AirDNA", data_atualizacao: "2026-03-01" },
  { id: 6, bairro: "Moema", cidade: "São Paulo", periodo_inicio: "2025-01", periodo_fim: "2025-12", n_listings_total: 380, n_listings_studio_1q: 150, pct_studio_1q: 39.5, adr_medio_studio: 300, ocupacao_media_studio: 0.77, receita_anual_media_studio: 84315, estadia_media_noites: 3.0, porcentagem_reservas_30d_plus: 7, rating_medio: 4.6, percentual_superhost: 38, media_reviews_por_listing: 26, pct_politica_flexivel: 58, pct_politica_moderada: 32, pct_politica_rigida: 10, preco_m2_residencial_medio: 13000, aluguel_mensal_long_term_medio: 3800, dias_medio_venda_imovel: 100, numero_transacoes_imobiliarias_ano: 950, indice_criminalidade: 2.2, grau_saturacao_index: 42, risco_regulatorio: 2, risco_condominio: 2, area_media_estudio: 29, yield_bruto_airbnb: 0.125, yield_bruto_long_term: 0.068, delta_yield: 0.057, score_rentabilidade: 74, score_liquidez: 75, score_crescimento_potencial: 72, nivel_confianca_dados: "alto", fonte_primaria: "AirDNA", data_atualizacao: "2026-03-01" },
  { id: 7, bairro: "Brooklin", cidade: "São Paulo", periodo_inicio: "2025-01", periodo_fim: "2025-12", n_listings_total: 320, n_listings_studio_1q: 130, pct_studio_1q: 40.6, adr_medio_studio: 290, ocupacao_media_studio: 0.75, receita_anual_media_studio: 79388, estadia_media_noites: 3.1, porcentagem_reservas_30d_plus: 9, rating_medio: 4.5, percentual_superhost: 32, media_reviews_por_listing: 24, pct_politica_flexivel: 62, pct_politica_moderada: 28, pct_politica_rigida: 10, preco_m2_residencial_medio: 12000, aluguel_mensal_long_term_medio: 3500, dias_medio_venda_imovel: 110, numero_transacoes_imobiliarias_ano: 780, indice_criminalidade: 2.8, grau_saturacao_index: 38, risco_regulatorio: 2, risco_condominio: 3, area_media_estudio: 27, yield_bruto_airbnb: 0.12, yield_bruto_long_term: 0.065, delta_yield: 0.055, score_rentabilidade: 70, score_liquidez: 70, score_crescimento_potencial: 78, nivel_confianca_dados: "médio", fonte_primaria: "AirDNA", data_atualizacao: "2026-03-01" },
  { id: 8, bairro: "República", cidade: "São Paulo", periodo_inicio: "2025-01", periodo_fim: "2025-12", n_listings_total: 450, n_listings_studio_1q: 280, pct_studio_1q: 62.2, adr_medio_studio: 200, ocupacao_media_studio: 0.72, receita_anual_media_studio: 52560, estadia_media_noites: 4.0, porcentagem_reservas_30d_plus: 15, rating_medio: 4.3, percentual_superhost: 18, media_reviews_por_listing: 18, pct_politica_flexivel: 75, pct_politica_moderada: 18, pct_politica_rigida: 7, preco_m2_residencial_medio: 7500, aluguel_mensal_long_term_medio: 2000, dias_medio_venda_imovel: 160, numero_transacoes_imobiliarias_ano: 400, indice_criminalidade: 5.5, grau_saturacao_index: 65, risco_regulatorio: 4, risco_condominio: 5, area_media_estudio: 22, yield_bruto_airbnb: 0.105, yield_bruto_long_term: 0.055, delta_yield: 0.05, score_rentabilidade: 60, score_liquidez: 55, score_crescimento_potencial: 60, nivel_confianca_dados: "médio", fonte_primaria: "AirDNA", data_atualizacao: "2026-03-01" },
  { id: 9, bairro: "Liberdade", cidade: "São Paulo", periodo_inicio: "2025-01", periodo_fim: "2025-12", n_listings_total: 280, n_listings_studio_1q: 120, pct_studio_1q: 42.9, adr_medio_studio: 220, ocupacao_media_studio: 0.73, receita_anual_media_studio: 58619, estadia_media_noites: 3.3, porcentagem_reservas_30d_plus: 11, rating_medio: 4.4, percentual_superhost: 22, media_reviews_por_listing: 20, pct_politica_flexivel: 68, pct_politica_moderada: 22, pct_politica_rigida: 10, preco_m2_residencial_medio: 8500, aluguel_mensal_long_term_medio: 2300, dias_medio_venda_imovel: 135, numero_transacoes_imobiliarias_ano: 450, indice_criminalidade: 4.0, grau_saturacao_index: 35, risco_regulatorio: 3, risco_condominio: 3, area_media_estudio: 24, yield_bruto_airbnb: 0.115, yield_bruto_long_term: 0.06, delta_yield: 0.055, score_rentabilidade: 66, score_liquidez: 62, score_crescimento_potencial: 68, nivel_confianca_dados: "médio", fonte_primaria: "AirDNA", data_atualizacao: "2026-03-01" },
  { id: 10, bairro: "Vila Olímpia", cidade: "São Paulo", periodo_inicio: "2025-01", periodo_fim: "2025-12", n_listings_total: 480, n_listings_studio_1q: 200, pct_studio_1q: 41.7, adr_medio_studio: 360, ocupacao_media_studio: 0.79, receita_anual_media_studio: 103806, estadia_media_noites: 2.6, porcentagem_reservas_30d_plus: 5, rating_medio: 4.6, percentual_superhost: 40, media_reviews_por_listing: 30, pct_politica_flexivel: 52, pct_politica_moderada: 38, pct_politica_rigida: 10, preco_m2_residencial_medio: 15000, aluguel_mensal_long_term_medio: 4600, dias_medio_venda_imovel: 85, numero_transacoes_imobiliarias_ano: 1100, indice_criminalidade: 2.6, grau_saturacao_index: 58, risco_regulatorio: 2, risco_condominio: 2, area_media_estudio: 31, yield_bruto_airbnb: 0.135, yield_bruto_long_term: 0.074, delta_yield: 0.061, score_rentabilidade: 78, score_liquidez: 80, score_crescimento_potencial: 70, nivel_confianca_dados: "alto", fonte_primaria: "AirDNA", data_atualizacao: "2026-03-01" },
];

export function useBairrosData() {
  return useQuery({
    queryKey: ["bairro_airbnb_sp"],
    queryFn: async () => MOCK_BAIRROS,
    staleTime: Infinity,
  });
}

export function useBairroDetail(bairro: string) {
  return useQuery({
    queryKey: ["bairro_airbnb_sp", bairro],
    queryFn: async () => {
      const found = MOCK_BAIRROS.find(b => b.bairro === bairro);
      if (!found) throw new Error(`Bairro ${bairro} not found`);
      return found;
    },
    enabled: !!bairro,
  });
}

export function useRawListings(_bairro?: string) {
  return useQuery({
    queryKey: ["raw_listings", _bairro],
    queryFn: async () => [] as any[],
    staleTime: Infinity,
  });
}

export const fmtBRL = (v: number) =>
  new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(v);

export const fmtPct = (v: number) => `${(v * 100).toFixed(1)}%`;

export const fmtScore = (v: number) => v?.toFixed(1) ?? "—";
