import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { motion } from "framer-motion";
import { Palette, Camera, Package, ShieldCheck, Star, MousePointerClick, CalendarCheck, MessageSquare, Trophy, DollarSign, ArrowRight } from "lucide-react";
import sectionDecoracao from "@/assets/section-decoracao.jpg";
import SectionBlock from "./SectionBlock";

export default function DecoracaoSection() {
  const pilares = [{ title: "Design autoral", desc: "Estética diferenciada que se destaca nas buscas", icon: Palette }, { title: "Fotos profissionais", desc: "Imagens que vendem — a primeira impressão do anúncio", icon: Camera }, { title: "Funcionalidade", desc: "Cada metro útil otimizado para o hóspede", icon: Package }, { title: "Durabilidade", desc: "Materiais que resistem ao uso intenso de short stay", icon: ShieldCheck }, { title: "Identidade de marca", desc: "Consistência visual que gera reviews e retorno", icon: Star }];
  const flywheel = [{ label: "Design", icon: Palette }, { label: "Fotos", icon: Camera }, { label: "Cliques", icon: MousePointerClick }, { label: "Reservas", icon: CalendarCheck }, { label: "Reviews", icon: MessageSquare }, { label: "Ranking", icon: Trophy }, { label: "Diária maior", icon: DollarSign }];
  const benefits = [{ value: "+25–30%", label: "diárias (potencial)" }, { value: "75–85%", label: "ocupação (potencial)" }, { value: "até +40%", label: "valorização (potencial)" }, { value: "6–12 meses", label: "payback (referência)" }];

  return (
    <SectionBlock id="decoracao" title="Decoração Estratégica" takeaway="Design que converte: estética + funcionalidade + rentabilidade.">
      <div className="rounded-2xl overflow-hidden mb-8 shadow-sm ring-1 ring-border"><img src={sectionDecoracao} alt="Studio decorado com design estratégico" className="w-full h-40 md:h-64 object-cover" loading="lazy" width={800} height={256} /></div>
      <h3 className="font-display text-xl font-bold text-foreground mb-4">Os 5 Pilares</h3>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-3 mb-8">{pilares.map((p) => <Card key={p.title} className="border-border"><CardContent className="p-4 flex items-start gap-3"><div className="h-9 w-9 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0"><p.icon className="text-primary" size={18} /></div><div><p className="font-semibold text-foreground text-sm">{p.title}</p><p className="text-xs text-muted-foreground mt-0.5">{p.desc}</p></div></CardContent></Card>)}</div>
      <h3 className="font-display text-xl font-bold text-foreground mb-4">O Flywheel da Rentabilidade</h3>
      <Card className="border-border mb-8"><CardContent className="p-6"><div className="flex flex-wrap items-center justify-center gap-2 md:gap-1">{flywheel.map((step, i) => <div key={step.label} className="flex items-center gap-1 md:gap-2"><motion.div className="flex flex-col items-center gap-1 px-3 py-2 rounded-lg bg-secondary min-w-[80px]" initial={{ opacity: 0, scale: 0.8 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} transition={{ delay: i * 0.08 }}><step.icon size={18} className="text-primary" /><span className="text-xs font-medium text-foreground">{step.label}</span></motion.div>{i < flywheel.length - 1 && <ArrowRight size={14} className="text-muted-foreground flex-shrink-0" />}</div>)}</div><p className="text-center text-xs text-muted-foreground mt-3">Ciclo virtuoso: cada etapa alimenta a próxima</p></CardContent></Card>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-4">{benefits.map((b) => <Card key={b.label} className="border-border"><CardContent className="p-4 text-center"><p className="text-xl font-display font-bold text-primary">{b.value}</p><p className="text-xs text-muted-foreground mt-1">{b.label}</p></CardContent></Card>)}</div>
      <div className="flex flex-wrap gap-2 text-sm text-muted-foreground font-body mb-2"><Badge variant="secondary" className="font-body">Menos manutenção</Badge><Badge variant="secondary" className="font-body">Operação simplificada</Badge><Badge variant="secondary" className="font-body">Reputação orgânica</Badge></div>
      <Accordion type="multiple" className="mt-4 font-body">
        <AccordionItem value="budget"><AccordionTrigger className="text-primary font-semibold">Budget breakdown por nível</AccordionTrigger><AccordionContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-border"><th className="text-left py-2 text-muted-foreground font-medium">Nível</th><th className="text-right py-2 text-muted-foreground font-medium">Investimento</th><th className="text-left py-2 pl-4 text-muted-foreground font-medium">O que inclui</th></tr></thead><tbody><tr className="border-b border-border/50"><td className="py-2 text-foreground font-medium">Básico</td><td className="py-2 text-right text-muted-foreground">R$ 15–25k</td><td className="py-2 pl-4 text-muted-foreground">Pintura, iluminação LED, mobília essencial, enxoval padrão, fotos com celular profissional</td></tr><tr className="border-b border-border/50"><td className="py-2 text-foreground font-medium">Premium</td><td className="py-2 text-right text-muted-foreground">R$ 25–40k</td><td className="py-2 pl-4 text-muted-foreground">Marcenaria planejada, iluminação cênica, mobília curada, enxoval premium, fotos profissionais, smart lock</td></tr><tr className="border-b border-border/50"><td className="py-2 text-foreground font-medium">Alto padrão</td><td className="py-2 text-right text-muted-foreground">R$ 40–60k</td><td className="py-2 pl-4 text-muted-foreground">Design autoral, marcenaria premium, piso vinílico/porcelanato, automação, arte original, styling completo, fotos + vídeo</td></tr></tbody></table></div></AccordionContent></AccordionItem>
        <AccordionItem value="roi-decoracao"><AccordionTrigger className="text-primary font-semibold">ROI por nível de decoração</AccordionTrigger><AccordionContent><p className="text-sm text-muted-foreground leading-relaxed"><strong className="text-foreground">Básico:</strong> payback de 10–14 meses. Melhora marginal na diária (+10-15%), mas custo baixo. <strong className="text-foreground">Premium:</strong> payback de 8–12 meses. Melhor custo-benefício — o aumento de diária (+20-30%) compensa o investimento adicional com folga. <strong className="text-foreground">Alto padrão:</strong> payback de 6–10 meses. Diária +30-45%, mas exige público-alvo compatível e bairro premium (Itaim, Pinheiros, Vila Olímpia). O nível Premium geralmente oferece o melhor retorno ajustado ao risco.</p></AccordionContent></AccordionItem>
      </Accordion>
    </SectionBlock>
  );
}
